kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: wordpress
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: wordpress
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: gcr.io/[PROJECT_ID]/wordpress:v1
        imagePullPolicy: Always
        ports:
        - name: wordpress
          containerPort: 80
